<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CISM532" name="TestNgScripts.LoginTest" tests="9" failures="0" timestamp="30 May 2019 13:19:36 GMT" time="35.810" errors="1">
  <testcase name="LogPageTS06" time="1.730" classname="TestNgScripts.LoginTest"/>
  <testcase name="LogPageTS07" time="4.139" classname="TestNgScripts.LoginTest"/>
  <testcase name="LogPageTS01" time="4.422" classname="TestNgScripts.LoginTest"/>
  <testcase name="LogPageTS09" time="10.004" classname="TestNgScripts.LoginTest"/>
  <testcase name="LogPageTS04" time="1.987" classname="TestNgScripts.LoginTest">
    <error type="java.lang.Error" message="Unresolved compilation problem: 
	headerLogout cannot be resolved or is not a field
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
headerLogout cannot be resolved or is not a field

at TestNgScripts.LoginTest.LogPageTS04(LoginTest.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- LogPageTS04 -->
  <testcase name="LogPageTS08" time="2.319" classname="TestNgScripts.LoginTest"/>
  <testcase name="LogPageTS03" time="6.484" classname="TestNgScripts.LoginTest"/>
  <testcase name="LogPageTS05" time="2.899" classname="TestNgScripts.LoginTest"/>
  <testcase name="LogPageTS02" time="1.826" classname="TestNgScripts.LoginTest"/>
</testsuite> <!-- TestNgScripts.LoginTest -->
